export const skappNames = {
  "arigale.hns": {
    name: "Arigale CMS",
    description: "Decentralized backend for schemas and post",
    github: "https://github.com/bhanupsingh77/arigale-cms",
    imageUrl: "/projects/Arigale.png",
  },
  "skytransfer.hns": {
    name: "SkyTransfer",
    description: "Encrypted file storage and sharing, across devices",
    github: "https://github.com/kamy22/skytransfer",
    imageUrl: "/projects/SkyTransfer1.png",
  },
  "skychess.hns": {
    name: "SkyChess",
    description: "Find an opponent or watch a chess match",
    developer: "redsolver",
    github: "https://github.com/redsolver/skychess",
    imageUrl: "/projects/SkyChess.png",
  },
  "giphyaf.hns": {
    name: "GiphyAF",
    description: "Create your GIF library on Skynet",
    github: "https://github.com/jordanpinski/giphyaf",
    imageUrl: "/projects/giphyaf.png",
  },
  "skybookmarks.hns": {
    name: "SkyBookmarks",
    description: "Save and view saved links",
    github: "https://github.com/michaelmuenzer/skybookmarks",
    imageUrl: "/projects/SkyBookmarks.png",
  },
  // "ozujw.hns.siasky.dev": {
  //   name: "SkyNetGram",
  //   description: "Shared feed for square images",
  //   github: "https://github.com/rajatbeladiya/SkyNetGram",
  //   link: "ozujw.hns",
  //   imageUrl: "/projects/SkynetGram.png",
  // },
  "webgames-ide.hns": {
    name: "Webgame IDE",
    description: "Create games and deploy them to Skynet",
    github: "https://github.com/ericflo/webgames-ide",
    imageUrl: "/projects/WebGamesIDE.png",
  },
  "0008ma52pgm6oac9qrj3fi5a202tcu590bs7es148n5e6mjm78n4it0": {
    name: "SVGUP",
    description: "Upload and Edit SVG Files",
    github: "https://github.com/lucasespinosa28/SVGUP",
    imageUrl: "/projects/SVGUp.png",
  },
  "0000chsgunr75ulvqcblsc61bag320tf32peqjra2vs8vrob3gj8lp0": {
    name: "SkynetClient API Usage",
    description: "Play around with skynet-js API",
    github: "https://github.com/antonyip/ss-api",
  },
  "tirthahalli.hns": {
    name: "How About Skapp",
    description: "Propose and vote on ideas",
    github: "https://github.com/devAttila87/siasky-habout",
    imageUrl: "/projects/Habout.png",
    // wip: true,
  },
  "0004m25ifbub93sj9itg9po8ptd78lke2bqhbj3qo4eekd42ocdlh88": {
    name: "How About Skapp",
    description: "Propose and vote on ideas",
    github: "https://github.com/devAttila87/siasky-habout",
    imageUrl: "/projects/Habout.png",
    hidden: true,
    // wip: true,
  },
  // // Below shouldn't appear after new leaderboard rules.
  localhost: { hidden: true },
  "snew.hns": {
    name: "Skynet Workshop",
    description: "Project built to teach developers Skynet and MySky",
    github: "https://github.com/SkynetLabs/skynet-workshop",
  },
  // "skytter.hns": {
  //   name: "SkyChess",
  //   description: "Find an opponent or watch a chess match",
  //   developer: "redsolver",
  //   github: "https://github.com/redsolver/skychess",
  //   wip: true,
  // },
  "metformin10.hns": {
    name: "SkyNetGram",
    description: "Shared feed for square images",
    imageUrl: "/projects/SkynetGram.png",
    github: "https://github.com/rajatbeladiya/SkyNetGram",
  },
  // "000039hsk30kqji7a52014da9sr5pujkp3nnneufi5ghd9ieaul7pdo": {},
  // "0001pdr6q7bk35vqc3rsta9pvh09r32hogbvprvdjkeoa0sgkinedm8": {},
  // "600ci0qbat6kpl15ff16qbkh6dr7gk1qbdpi0gusprg5779gj7l24k0": {
  //   name: "SkyGames SDK",
  //   wip: true,
  //   description: "SDK for Connecting Skynet and Unity",
  //   github: "https://github.com/figurestudios/SkyGameSDK",
  // },
  // "00071mk4hmbg2m0s2m9n957s1j23ro89ele1f7dkve6c5fvb09j788g": {
  //   name: "Arigale CMS",
  //   description: "Decentralized backend for schemas and post",
  //   github: "https://github.com/bhanupsingh77/arigale-cms",
  //   wip: true,
  // },
};
