name: Deploy to Skynet

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 15.x

      - name: Install dependencies
        run: yarn

      - name: Build website
        run: yarn build
        env:
          REACT_APP_GIT_SHA: ${{ github.sha }}
          REACT_APP_API_URL: https://dev1.siasky.dev/leaderboard

      - name: Deploy to Skynet
        uses: kwypchlo/deploy-to-skynet-action@main
        with:
          upload-dir: build
          github-token: ${{ secrets.GITHUB_TOKEN }}
          registry-seed: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' && secrets.REGISTRY_SEED || '' }}
